#!/bin/sh
pdfbook --short-edge --paper letterpaper  --noautoscale 'true' --outfile ~/Desktop/temp.pdf -- "$1"
filename=$(basename "$1")
fname="${filename%.*}"
mv ~/Desktop/temp.pdf ~/Desktop/"$fname-booklet.pdf"
